site_name: Atlas Docs
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
      # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Inter
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Atlas-OS
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/atlas-795710270000332800
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
